### ISSUE TITLE
Error code: 500 after build & run (React-Native)

### ISSUE THREAD

**Issue by tandemasia** [BugBattle/ReactNative-SDK#10] opened 2021-01-25 04:26 UTC
Hi,

I have an issue like screenshot below:

<img width="882" alt="Screenshot 2021-01-25 at 12 17 38" src="https://user-images.githubusercontent.com/49545959/105661416-524bab80-5f08-11eb-8dc4-4abe7fd5479f.png">

Tried to build and run several time but still get this error.

Can anyone here to share the solutions.

Thanks!!

**Comment by niklasfessler** [comment] 2021-01-25 06:04
Hey :)

I take a look now and figure out what the problem. Just give me some time 😌

Greetings Niklas

**Comment by niklasfessler** [comment] 2021-01-25 06:18
@tandemasia can you please write me your babel and react native version?

Greetings Niklas

**Comment by tandemasia** [comment] 2021-01-25 06:28
Hi @niklasfessler ,

Here is the version:
"react-native": "^0.57.8"
"babel-core": "^6.26.3"

Thanks!

**Comment by niklasfessler** [comment] 2021-01-25 10:19
Do you have an . babelrc? From my side it looks like a miss match with the babel configuration

Greetings Niklas

**Comment by tandemasia** [comment] 2021-01-25 10:41
Here is the content of my .babelrc file

{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-nullish-coalescing-operator"
  ],
  "presets": ["react-native"]
}

Thanks!

**Comment by tandemasia** [comment] 2021-01-25 15:46
Hi Niklas, I did add the presets from above.

But right now , have another issue as below:

<img width="976" alt="Screenshot 2021-01-25 at 23 39 52" src="https://user-images.githubusercontent.com/49545959/105728763-7c808600-5f67-11eb-9bdf-6aa53217e3cb.png">

Thanks!

**Comment by niklasfessler** [comment] 2021-01-25 16:02
Hm i think you need to update babel. THe imports + exports was added in 7.9.0. Can you please upgrade? And try to :

npm start -- --reset-cache

Greetings Niklas

**Comment by tandemasia** [comment] 2021-01-26 02:21
Hi @niklasfessler ,

I did update to this "@babel/preset-typescript": "^7.12.7" & reset cache, but the problem still remain the same.

Thanks!

**Comment by niklasfessler** [comment] 2021-01-26 08:06
Is your project public? Can i get access on that? Then i can check directly what the problem is?

Greetings Niklas

**Comment by tandemasia** [comment] 2021-01-26 09:11
Hi @niklasfessler, 

Our project cannot be access publicly. Is there any way I can talk personally with you?

Thanks!

**Comment by niklasfessler** [comment] 2021-01-26 09:30
Hey can you send me an email so i can invite you to an meeting? niklas@bugbattle.io

Greetings Niklas

**Comment by niklasfessler** [comment] 2021-02-01 09:08
This is fixed in the new version

Greetings Niklas

**Closed by niklasfessler** 2021-02-01 09:08 UTC
